<a href="https://colab.research.google.com/github/Prakharprasun/ml-ws-tryout-demo/blob/main/Numpy_14101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [3]:
import random

In [5]:
np.random.randint(low=100000,high=9999999,size=(1))

array([1987225])

In [14]:
import numpy as np
d_arr =np.random.randint(low=100000,high=9999999,size=(4,3))
print(d_arr)

[[ 192351 7742122 2233456]
 [1858810 4453384 7997780]
 [9207145  304480 1572906]
 [6677440 7158955  526479]]


In [31]:
d_arr =np.random.randint(low=100000,high=9999999,size=(20,20))
print(d_arr)

[[1205686 9486835 6681321 7064100 5202045 4873710 4139483  394067 8598148
  4616413 2983753 2496277 1094569 6740318 6533785 5141496 2075447 8282268
  9766636  861743]
 [1785401 3224261 6448209 8163415 7600669 8873682 3294704 7056590 4105668
  9107065 1701167 3565881 5130734 9326733 5829179 2663314 1673703 7967308
  3412156  275658]
 [ 993405 6630800 7454792 5286082 5084358 4232916 5411054 5818723 2915656
   126959 5338517 3165692 3135363 8886221 2122915 9195369 4390647 5741078
  8729831 7368594]
 [7171730 4804574 8987764 3325579 5003610 8143379  289913 2484571 6968070
  1545160 8164406  187174 9587641 9293043  470586 3351356 6293630 6586473
  3288476 7884443]
 [ 415729  884996 2502742 4347897 9353641 7062069 9536791 7229300 7897775
  6647072 8211502 6918333  754827 1954730 9434064 9279840 9860902 3394374
  2462021 1967205]
 [2720398 2053915 3638307 9718516 5370102 3384390 8377632 8964030 1138145
  4173949 2700821  514780 9900715 1703023 2093250 3440683 8580694 8546923
  5801786 2196252

In [12]:
4571976 in d_arr

True

In [15]:
d_arr.max()

9207145

In [16]:
d_arr.std()

3265488.523322336

std = standard deviation

In [18]:
d_arr[3,5]

6609504

In [19]:
d_arr[:,:3]

array([[9458860, 3725840, 6755785],
       [3322112, 9331632,  147670],
       [ 179165, 3235288, 2013541],
       [5781547, 5052152,  358955],
       [6703032, 4964509, 3187086],
       [4654266, 6725243, 7349106],
       [6731379, 6534419, 5149858],
       [1808337, 5908194, 2315157],
       [7799256,  512179, 7081295],
       [9816570, 2922524,  576254],
       [8425055, 4102477,  207391],
       [6086594, 4017511, 1960487],
       [8523727, 4568074,  237265],
       [9912508, 4170666, 4559163],
       [8216393,  142033, 2724379],
       [4441414, 5819149, 6233876],
       [7625545, 7777347, 4843042],
       [ 534108, 3513247, 1577079],
       [8210157, 2734364, 4762661],
       [5928406, 5309268, 1143508]])

In [26]:
d_arr[:2,:3]

array([[8309161, 1630408, 7392735],
       [7167492, 4158011, 2532001]])

In [27]:
d_arr[10:12,8:13]

array([[3302050, 8803563, 5119275, 8284710, 3332139],
       [3690119, 9637928,  250343, 9443466, 2743104]])

In [32]:
d_arr[-8:-5,-9:-5]

array([[4558566, 8993599, 7974084,  937483],
       [5872748, 5692186, 2230769, 8241271],
       [9098311, 4616636, 3634677, 9151092]])